### ISSUE TITLE
Documentation github page 404

### ISSUE THREAD

**Issue by aeischeid** [antony/grails-oauth-scribe#40]
https://aiten.github.com/grails-oauth-scribe/ is showing a 404 for me. I can still get at some of it by looking at the gh-pages branch, but just thought you might want to know :)

**Comment by kdorff** [comment]
Hi,

I'd love to recommend this plugin, as it mostly seems to work for me but.

1. The Grails plugin site points to the wrong URL. (see above, already discussed).

2. Documentation. The old version (at the now broken URL) had SOME documentation. This now has non. How am I supposed to figure out the in's and out's of using this plugin? I did get it working, but am I doing everything right?

3. Documentation. I was able to get a an access_token and tokeninfo, but how do I refresh the token? The missing documentation makes it hard to figure out. I refreshed my page over and over until the token expired and then my token was just expired and the user has to login again. When the token is expired or about to, I thought maybe the library would refresh it for me. No idea.

Thanks,
Kevin

**Comment by antony** [comment]
My bad - not sure why github isn't showing me this problem. I renamed from aiten -> antony a few months ago and I haven't updated the plugin to reflect the new url. Sorry!

As for token refreshing, because there is no 'standard' for this, you have to figure out how your provider implements it and do it yourself. All the tokens you need are available to your application after initial connect. If you have a solution for this I'd be pleased to hear about it!
